### ISSUE TITLE
Question regarding html2pdf.it

### ISSUE THREAD

**Issue by ghost** [edm00se/ama#6]
Hi Eric, I basically saw that you commented on a few of the issues regarding html2pdf.it. It's probably a longshot but I checked your website and saw you have this ask me anything, so what the hell eh?

I am using html2pdf.it (h2p) on my development server and everything worked perfectly, styling, images, etc. but that server is http. When I moved the updates of the project to the live server https, h2p gave me the error message Unable to load the address (null): {url} fail. My web project redirects everything through index.php and lets that file decide where to go. All of the files referenced throughout the project are https and I notice that the url for h2p is http://www.html2pdf.it; is that the issue? Do you think my project doesn't like that the website converting my page to pdf is non ssl? Is there something I can do in my .htaccess file to get this working? I'm not exactly sure the issue at this point.

Sorry for bothering you and thank you for your time!
Daniel Speer

**Comment by edm00se** [comment]
Hi Daniel. [Your account seems to have been ghosted](https://github.com/speerzy), so this seems somewhat dubious, but I'll assume all is with good intention.

Since this is a question unique to the html2pdf.it project, the best location for it would be there (in the source git repository), most likely related to [ebdrup/html2pdf.it#61](https://github.com/apilayer/html2pdf.it/issues/61). Since there seems to be similar to that issue, it _might_ have something to do with the use of https; the biggest counterargument is that while that example and yours don't work, [the encrypted google search page over https](http://www.html2pdf.it/?url=https%3A%2F%2Fencrypted.google.com&download=false&format=A4&downloadToken=1504194201129&orientation=portrait&margin=1cm) works fine (from the html2pdf.it site on http). I suspect some nuances are involved, so if you can post back specifics as to your live server, we might be able to talk specifics. Please open an issue on the project repo's issue tracker or ride into the already reported [ebdrup/html2pdf.it#61](https://github.com/apilayer/html2pdf.it/issues/61).

Mixed content rules mean that from http you can include https assets, but the other way around (http on an https site) will yield warnings or fail to load (depending on the browser). For literature, here's [MDN's page on mixed content and web security][mdn-mixed-content-sec].

Thanks for asking and best of luck!

[mdn-mixed-content-sec]:https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by edm00se** [comment]
Twitter thread of some follow up:
https://twitter.com/edm00se/status/903355929885904896
